### ISSUE TITLE
Add extended logging during transaction flow

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/swarm-control#11]
In order to catch any possible issues and make sure people aren't scammed, we should add very detailed logging to the transaction flow

**Comment by Alexejhero** [comment]
This logging should be added to both the ebs and the FE, however im not sure exactly how to handle FE logging.

Possible idea: have a dedicated logging server in case the EBS server crashes. EBS can generate a temporary logging token that the FE can use during a transaction flow. (Sounds very complicated)

**Comment by Govorunb** [comment]
mmmm analytics nom nom data
> have a dedicated logging server in case the EBS server crashes

how it works generally on the big bad websites that track you is:
- the client generates event objects locally into a store (array)
- then periodically (pls random offset to not ddos) sends it over to the analytics endpoint
  - if sent successfully, clear the store
- (optionally) save unsent events to local/session storage in case they lose an order and then close the tab in pure rage

in order to actually make sure we can fulfill transactions we need to
- generate a unique but short (pronouncable) "order id"
- tag everything relevant with it
- display it to the client

that way if something goes wrong they can DM it to you and we can correlate it with an actual real order that occurred (or didn't)
it's only as complicated as putting a string into a ~~dict~~ map keyed on channel id (it's a slight bit more complicated)

your call on whether any of these make sense

**Comment by Alexejhero** [comment]
Logging implementation finished in backend, still need to add some more error handling but that's a part of #12 I guess.
Frontend still needs to be done
